version: '3'
services:
    nodejs:
        container_name: ${APP_NAME}_nodejs
        build: .
        command: npm run dev
        environment:
            - NODE_ENV=${NODE_ENV}
            - PORT=${SERVER_PORT}
        volumes:
            - ./code:/var/www
            - /var/www/node_modules
        ports:
            - ${SERVER_PORT}:3000
        depends_on:
            - mongodb

    mongodb:
        container_name: ${APP_NAME}_mongodb
        build: ./mongodb
        volumes: 
            - mongodata:/data/db
            - ./mongodb/log:/data/log  
        ports:
            - 27017:27017
            
volumes: 
    mongodata: